In [1]:
import pandas as pd
import numpy as np

In [16]:
books = pd.read_csv('books.csv')

In [17]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    90 non-null     object
 1   author   90 non-null     object
 2   genre    90 non-null     object
 3   year     90 non-null     int64
 4   rating   90 non-null     float64
 5   summary  90 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.3+ KB

In [18]:
books.nunique()

title      80
author     63
genre      54
year       71
rating     10
summary    80
dtype: int64

In [19]:
books.isnull().sum()

title      0
author     0
genre      0
year       0
rating     0
summary    0
dtype: int64

In [20]:
books = books.dropna()

In [21]:
books.isnull().sum()

title      0
author     0
genre      0
year       0
rating     0
summary    0
dtype: int64

In [22]:
books.nunique()

title      80
author     63
genre      54
year       71
rating     10
summary    80
dtype: int64

In [23]:
books['summary'] = books['summary'].apply(lambda x:x.split())

In [24]:
books.head()

,title,author,genre,year,rating,summary
0,Harry Potter and the Philosopher's Stone,J K Rowling,Fiction,1997,3.0,"[A, boy, discovers, he, is, a, wizard, and, be..."
1,The Great Gatsby,F. Scott Fitzgerald,Fiction,1925,5.0,"[Narrator, Nick, Carraway, observes, millionai..."
2,1984,George Orwell,Dystopian,1949,4.7,"[In, a, totalitarian, surveillance, state,, Wi..."
3,To Kill a Mockingbird,Harper Lee,Fiction,1960,3.0,"[Scout, Finch, recounts, her, Depression‑era, ..."
4,Pride and Prejudice,Jane Austen,Romance,1813,4.6,"[Elizabeth, Bennet, navigates, class,, marriag..."

In [25]:
books['author'] = books['author'].apply(lambda x:x.replace(" ", ""))

In [26]:
books.head()

,title,author,genre,year,rating,summary
0,Harry Potter and the Philosopher's Stone,JKRowling,Fiction,1997,3.0,"[A, boy, discovers, he, is, a, wizard, and, be..."
1,The Great Gatsby,F.ScottFitzgerald,Fiction,1925,5.0,"[Narrator, Nick, Carraway, observes, millionai..."
2,1984,GeorgeOrwell,Dystopian,1949,4.7,"[In, a, totalitarian, surveillance, state,, Wi..."
3,To Kill a Mockingbird,HarperLee,Fiction,1960,3.0,"[Scout, Finch, recounts, her, Depression‑era, ..."
4,Pride and Prejudice,JaneAusten,Romance,1813,4.6,"[Elizabeth, Bennet, navigates, class,, marriag..."

In [27]:
books['genre'] = books['genre'].apply(lambda x:x.split(","))

In [28]:
books['author'] = books['author'].apply(lambda x:[x])

In [29]:
books.head(40)

,title,author,genre,year,rating,summary
0,Harry Potter and the Philosopher's Stone,[JKRowling],[Fiction],1997,3.0,"[A, boy, discovers, he, is, a, wizard, and, be..."
1,The Great Gatsby,[F.ScottFitzgerald],[Fiction],1925,5.0,"[Narrator, Nick, Carraway, observes, millionai..."
2,1984,[GeorgeOrwell],[Dystopian],1949,4.7,"[In, a, totalitarian, surveillance, state,, Wi..."
3,To Kill a Mockingbird,[HarperLee],[Fiction],1960,3.0,"[Scout, Finch, recounts, her, Depression‑era, ..."
4,Pride and Prejudice,[JaneAusten],[Romance],1813,4.6,"[Elizabeth, Bennet, navigates, class,, marriag..."
5,The Catcher in the Rye,[J.D.Salinger],[Fiction],1951,5.0,"[Holden, Caulfield, wanders, New, York, after,..."
6,The Hobbit,[J.R.R.Tolkien],[Fantasy],1937,4.5,"[Homebody, Bilbo, Baggins, joins, dwarves, and..."
7,Moby-Dick,[HermanMelville],[Adventure],1851,4.0,"[Sailor, Ishmael, recounts, Captain, Ahab’s, o..."
8,War and Peace,[LeoTolstoy],[Historical Fiction],1869,4.6,"[Through, several, aristocratic, families,, To..."
9,Crime and Punishment,[FyodorDostoevsky],[Psychological Fiction],1866,4.0,"[Raskolnikov, murders, a, pawnbroker, to, test..."
10,Anna Karenina,[LeoTolstoy],[Fiction],1877,4.3,"[Anna’s, illicit, love, for, Vronsky, clashes,..."
11,Frankenstein,[MaryShelley],[Gothic Fiction],1818,4.2,"[Victor, Frankenstein, creates, a, living, bei..."
12,The Picture of Dorian Gray,[OscarWilde],[Philosophical Fiction],1890,4.3,"[Dorian, remains, youthful, while, his, hidden..."
13,Dracula,[BramStoker],[Horror],1897,4.1,"[Told, through, diaries, and, letters,, a, ban..."
14,The Odyssey,[Homer],[Epic Poetry],-800,4.4,"[Odysseus, spends, ten, perilous, years, retur..."
15,The Divine Comedy,[DanteAlighieri],[Epic Poetry],1320,4.2,"[Dante, journeys, through, Hell,, Purgatory,, ..."
16,The Brothers Karamazov,[FyodorDostoevsky],[Philosophical Fiction],1880,4.5,"[A, sprawling, philosophical, drama, of, faith..."
17,The Stranger,[AlbertCamus],[Existentialism],1942,4.4,"[Meursault’s, emotional, detachment, culminate..."
18,Harry Potter and the Chamber of Secrets,[JKRowling],[Fantasy],2002,5.0,"[Harry’s, second, year, at, Hogwarts, brings, ..."
19,Percy Jackson & the Olympians: The Lightning T...,[RickRiordan],"[Fantasy, Young adult, Mythology]",2005,5.0,"[A, modern, teen, discovers, he’s, a, demigod,..."
20,The Golden Compass,[PhilipPullman],[Fantasy],1995,4.0,"[Lyra, Belacqua, journeys, north, to, rescue, ..."
21,Eragon,[ChristopherPaolini],"[Fantasy, Young adult]",2002,5.0,"[A, farm, boy, discovers, a, dragon, egg,, for..."
22,This Side of Paradise,[F.ScottFitzgerald],[Bildungsroman],1920,5.0,"[Amory, Blaine’s, coming‑of‑age, across, Ivy, ..."
23,The Sun Also Rises,[ErnestHemingway],"[Literary fiction, Modernist]",1926,5.0,"[Expatriates, drift, through, postwar, Europe,..."
24,The Age of Innocence,[EdithWharton],[Novel of manners],1920,5.0,"[Gilded, Age, New, York, tests, love, and, dut..."
25,Brave New World,[AldousHuxley],"[Dystopian, Science fiction]",1932,5.0,"[A, genetically, engineered, society, trades, ..."
26,Fahrenheit 451,[RayBradbury],"[Dystopian, Science fiction]",1953,5.0,"[A, fireman, who, burns, books, begins, to, qu..."
27,We,[YevgenyZamyatin],"[Dystopian, Science fiction]",1924,5.0,"[A, citizen, of, a, mechanized, future, writes..."
28,Animal Farm,[GeorgeOrwell],"[Political satire, Allegory]",1945,5.0,"[A, barnyard, rebellion, becomes, a, fable, of..."
29,Go Set a Watchman,[HarperLee],"[Southern Gothic, Historical]",2015,5.0,"[An, adult, Scout, returns, to, Maycomb, and, ..."
30,A Time to Kill,[JohnGrisham],[Legal thriller],1989,5.0,"[A, lawyer, defends, a, Black, father, who, ki..."
31,The Secret Life of Bees,[SueMonkKidd],"[Coming-of-age, Historical]",2001,5.0,"[A, girl, finds, solace, in, a, beekeeping, si..."
32,The Adventures of Huckleberry Finn,[MarkTwain],"[Picaresque, Satire]",1884,5.0,"[A, boy, and, a, runaway, slave, raft, down, t..."
33,Emma,[JaneAusten],"[Romance, Novel of manners]",1815,5.0,"[A, well‑meaning, matchmaker, meddles, her, wa..."
34,Wuthering Heights,[EmilyBrontë],"[Gothic fiction, Tragedy]",1847,5.0,"[A, fierce,, doomed, love, haunts, generations..."
35,Jane Eyre,[CharlotteBrontë],"[Gothic romance, Bildungsroman]",1847,5.0,"[An, orphaned, governess, finds, love, and, se..."
36,North and South,[ElizabethGaskell],"[Social novel, Romance]",1855,5.0,"[A, Southern, woman, confronts, class, strife,..."
37,The Bell Jar,[SylviaPlath],"[Semi-autobiographical, Coming-of-age]",1963,5.0,"[A, young, writer’s, descent, into, depression..."
38,On the Road,[JackKerouac],"[Beat literature, Picaresque]",1957,5.0,"[Beat‑era, wanderers, chase, freedom, across, ..."
39,A Separate Peace,[JohnKnowles],"[Coming-of-age, War fiction]",1959,5.0,"[Friendship, and, rivalry, at, a, New, England..."

In [30]:
books['tags'] = books['author'] + books['genre'] + books['summary']

In [49]:
new_df = books[['title', 'tags']]

In [50]:
new_df.head()

,title,tags
0,Harry Potter and the Philosopher's Stone,"[JKRowling, Fiction, A, boy, discovers, he, is..."
1,The Great Gatsby,"[F.ScottFitzgerald, Fiction, Narrator, Nick, C..."
2,1984,"[GeorgeOrwell, Dystopian, In, a, totalitarian,..."
3,To Kill a Mockingbird,"[HarperLee, Fiction, Scout, Finch, recounts, h..."
4,Pride and Prejudice,"[JaneAusten, Romance, Elizabeth, Bennet, navig..."

In [56]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\USER\AppData\Local\Temp\ipykernel_13484\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [57]:
new_df.head()

,title,tags
0,Harry Potter and the Philosopher's Stone,JKRowling Fiction A boy discovers he is a wiza...
1,The Great Gatsby,F.ScottFitzgerald Fiction Narrator Nick Carraw...
2,1984,GeorgeOrwell Dystopian In a totalitarian surve...
3,To Kill a Mockingbird,HarperLee Fiction Scout Finch recounts her Dep...
4,Pride and Prejudice,JaneAusten Romance Elizabeth Bennet navigates ...

In [58]:
new_df['tags'].apply(lambda x:x.lower())

0     jkrowling fiction a boy discovers he is a wiza...
1     f.scottfitzgerald fiction narrator nick carraw...
2     georgeorwell dystopian in a totalitarian surve...
3     harperlee fiction scout finch recounts her dep...
4     janeausten romance elizabeth bennet navigates ...
                            ...
85    franzkafka absurdist  psychological josef k. f...
86    jean-paulsartre philosophical fiction  existen...
87    fyodordostoevsky philosophical fiction a spite...
88    j.k.rowling fantasy  young adult harry must fi...
89    christopherpaolini fantasy  young adult a farm...
Name: tags, Length: 90, dtype: object

In [59]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [60]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    s = " ".join(y)
    return s

In [61]:
new_df['tags'].apply(stem)

0     jkrowl fiction a boy discov he is a wizard and...
1     f.scottfitzgerald fiction narrat nick carraway...
2     georgeorwel dystopian in a totalitarian survei...
3     harperle fiction scout finch recount her depre...
4     janeausten romanc elizabeth bennet navig class...
                            ...
85    franzkafka absurdist psycholog josef k. face a...
86    jean-paulsartr philosoph fiction existenti a d...
87    fyodordostoevski philosoph fiction a spite nar...
88    j.k.rowl fantasi young adult harri must find o...
89    christopherpaolini fantasi young adult a farm ...
Name: tags, Length: 90, dtype: object

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [66]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [67]:
vectors.shape

(90, 674)

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

In [69]:
similarity = cosine_similarity(vectors)

In [70]:
def recommend(book):
    book_index = new_df[new_df['title'] == book].index[0]
    distances = similarity[book_index]
    book_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]

    for i in book_list:
        print(new_df.iloc[i[0]].title)

In [71]:
import pickle

In [72]:
pickle.dump(new_df.to_dict(), open('booksAI.pkl', 'wb'))

In [73]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [76]:
recommend('Harry Potter and the Chamber of Secrets')

Harry Potter and the Philosopher's Stone
Harry Potter and the Prisoner of Azkaban
The Name of the Wind
A Wizard of Earthsea
The Fellowship of the Ring